theme: jekyll-theme-hacker
title: Marco Moriggi's technical website
description: Wellcome! Here you'll find some Java code man... get ready for dissertations on code tuning, performance analysis and some useless advice and "TL;DR;"s
